extends:
  - axway/env-node
  - axway/env-titanium
plugins:
  - mocha
env:
  mocha: true
globals:
  expect: readonly
parserOptions:
  ecmaVersion: 2019
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
      - modules
